### PR TITLE
Detect langs based on substrings

### LINKED ISSUE #2: PR to also detect translation languages?
Hi @ClaudiuCeia! Love this repo, great work!

Would you be interested in a PR to detect which natural language the page is translated into even if the translator hasn’t changed the `lang` attribute to say so (which includes many translators, including Papago and most Chinese ones; also many common browser extensions)?

I’ve written some code that does this and should be able to contribute it. It also detects additional translators, including more Chinese ones (Caiyun, QQ Browser, Sogou and Youdao) and can output a language tag like `zh-t-en-t0-baidu` (using the [BCP 47 T extension](https://www.unicode.org/reports/tr35/#t_Extension)) indicating that the content is translated and by which translation service, which is useful for analytics.

The natural language detection is very lightweight (1–2 KB) and uses substrings unique to each language, produced from known translations of a phrase. The source phrase I have used is “Skip to main content”, which is present on many sites as it is [a recommended technique](https://www.w3.org/TR/WCAG20-TECHS/G1.html#G1-ex2) to meet the [WCAG 2.1 accessibility requirement 2.4.1 Bypass Blocks](https://www.w3.org/TR/WCAG21/#bypass-blocks). (The algorithm can also produce unique substrings for translations of any other phrase, of course.)

Let me know if you would like a PR!

### PR DESCRIPTION
**Pull request by DuncanMacWeb**
Hi again! Hopefully this makes sense but there’s quite a lot here, let me know if you have questions about anything. The substrings themselves are generated from the translation source file at build time. I’ve refactored the API a bit too, hopefully not too much. There are also notes, including `TODO:` comments in places. Happy to refactor/remove anything!

This closes #2.

### CODE REVIEW

**Comment by ClaudiuCeia** [comment]
Thanks! I'll take a look tonight, I'm a bit caught with work now :)

**Comment by DuncanMacWeb** [comment]
I think it would make sense to “squash and merge” this PR once we’re happy with it btw (in the dropdown on the “Merge pull request” button).

**Comment by DuncanMacWeb** [comment]
@ClaudiuCeia I’m happy with this branch now, so I’m minded to merge, shout if you have any changes in mind!

**Comment by DuncanMacWeb** [comment]
Hope all is good with you @ClaudiuCeia. I’ll go ahead and merge tomorrow if there are no changes to make 👍

**Pull request merged**
